### PR TITLE
Reduce README length

### PR DESCRIPTION
**Pull request by m8m5**
Limitation:
 - no [windows](https://github.com/therecipe/qt#windows), [linux](https://github.com/therecipe/qt#linux) installation type links as they have became summery
 - links inside summary will not work e.g [linux optional](https://github.com/therecipe/qt#optional-cross-compile-for-windows-on-debianubuntu-experimental)

I hope that they are minor problem as README length reduce much. user will find easily from [Instructions](https://github.com/m8m5/qt#instructions).

### CODE REVIEW

**Comment by therecipe** [comment]
Nice!
Thank you :)
I didn't know that it was possible to create summaries.
It was initially planned to split the readme at some point after it would have been updated/rewritten (https://github.com/therecipe/qt/tree/master/internal/docs), but maybe I can use summaries instead to structure it.

And no worry about the removed links, those were just there as a work around for the length problem.

**Comment by m8m5** [comment]
You're welcome.

did you notice that installation step number became `Roman numerals`. I don't how to fix them (may be github parsing problem). I forgot to mention it.

**Comment by m8m5** [comment]
`summary` and `details` in README doesn't work in my `Microsoft Edge` and `Internet Explorer`.

it works in `opera`, `firefox`,  `vivaldi` and `google chrome` (other chromium based browser should work); I haven't tested it in `safari`.

**Comment by therecipe** [comment]
>did you notice that installation step number became Roman numerals. I don't know how to fix them (may be github parsing problem; I open a issue for that github/markup#991). I forgot to mention it.

ah, yes the lists were different somehow, but it didn't bothered me that much.
thanks for opening the issue though :)

>summary and details in README doesn't work in my Microsoft Edge and Internet Explorer.
it works in opera, firefox, vivaldi and google chrome (other chromium based browser should work); I haven't tested it in safari.

it's probably unfolded on IE / Edge?
if so then it's not a big problem, as the windows instructions are the first ones and therefore easily visible.
but the downside is that they can't directly jump to the example anymore now.

and I can confirm that it's working on safari.

**Comment by m8m5** [comment]
> it's probably unfolded on IE / Edge?

yes, it is unfolded on IE / Edge. may be _github will not use_ something like [details-shim](https://github.com/tyleruebele/details-shim). but i will contact them.

> but the downside is that they can't directly jump to the example anymore now.

> vi.  Create your first [application](https://github.com/therecipe/qt#example)

they can use step `vi` as before. so, i think it is not a problem.

**Comment by therecipe** [comment]
>they can use step vi as before to directly jump to the example. so, i think it is not a problem.

oh, yes you are right, it works :)
sorry, it somehow didn't worked when I first tried it.

**Pull request merged**
