### PR TITLE
Added support for Android NDK r20

### PR DESCRIPTION
**Pull request by angiglesias**
This patch adds the required flag to clang when Android NDK r20 is used

Detailed information: https://bugreports.qt.io/browse/QTBUG-76293

### CODE REVIEW

**Comment by therecipe** [comment]
Thank you!
I will test it and probably merge it tomorrow.
One thing thing I figured though, is that this will probably not work on Windows due the `sed` usage. But that's just a minor issue and can simply be solved by using the regexp pkg instead.

**Comment by angiglesias** [comment]
Sorry about the sed part. I totally forgot about compatibility with Windows!

**Comment by angiglesias** [comment]
I have reimplemented Android NDK sources.properties parsing to get the ndk version using regexp library instead of calling `sed`

**Comment by therecipe** [comment]
No worries, and also thank you very much :)
I will merge this now.

**Pull request merged**
